### ISSUE TITLE
Part 3: The docstring to the quiz "Rate of Returns Over Multiple Periods" is misleading.

### ISSUE THREAD

**Issue by sergei3000** [udacity/aitnd-issues#30] opened 2018-10-01 23:39 UTC
There are no tickers in the argument of the function calculate_arithmetic_rate_of_return().

**Comment by Brok-Bucholtz** [comment] 2018-10-09 19:28
This is a duplicate of issue #27.

**Closed as completed by Brok-Bucholtz** 2018-10-09 19:28 UTC
Labels: bug, duplicate
