### ISSUE TITLE
Error when running first cell of project 4 to install packages.

### ISSUE THREAD

**Issue by guireif** [udacity/aitnd-issues#104] opened 2019-03-13 21:44 UTC
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0m8fq6so/tables/
You are using pip version 9.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by AdrianoW** [comment] 2019-03-14 15:44
We have already mapped the problem with the table package. 
@Brok-Bucholtz is working on it

**Comment by Brok-Bucholtz** [comment] 2019-03-15 21:01
Duplicate of issue #102.

**Closed as completed by Brok-Bucholtz** 2019-03-15 21:01 UTC
