### ISSUE TITLE
Lesson 27 Pip 9 Min install subsequent lessons

### ISSUE THREAD

**Issue by AhmadRajab** [udacity/aitnd-issues#81] opened 2018-12-15 16:13 UTC
I pre-installed the 00_install_libraries which I understand is meant to speed up installs in subsequent notebooks but I'm finding that the pip install in subsequent workbooks is still taking approx9-10 mins so the pre instalation of 00_install_libraries hasn't worked as expected.

**Comment by e7dud7e** [comment] 2018-12-21 21:41
Hi Ahmad, thanks for letting us know.  Can you gives your email that you use with your Udacity account?  I can follow up with the engineering team about this.

**Comment by Brok-Bucholtz** [comment] 2019-01-25 22:30
This is a duplicate of Issue #85.

**Closed as completed by Brok-Bucholtz** 2019-01-25 22:30 UTC
Labels: duplicate
