### ISSUE TITLE
Project 2: test for `find_outliers()` not specific enough

### ISSUE THREAD

**Issue by arorasanu** [udacity/aitnd-issues#10] opened 2018-08-26 21:10 UTC
The current test for `find_outliers()` gets passed whether we take a union of the `ksvalue_outliers` and `pvalue_outliers`, or we take their intersection.

**Comment by pisymbol** [comment] 2018-09-24 11:03
The issue is the threshold values being used for the unit test. One of the thresholds should be raised so multiple stocks match while the other doesn't (that way an OR operation would get multiple stocks while an AND will only get the one true ticker expected by the unit test).

**Comment by fwulff** [comment] 2018-09-24 11:06
I second that! If students currently use OR or union instead of AND or intersection, they will still pass the tests, but find 299 outliers in the dataset instead of the correct 24 afterwards.

**Comment by Brok-Bucholtz** [comment] 2019-01-25 22:54
This is a duplicate of #9.

**Closed as completed by Brok-Bucholtz** 2019-01-25 22:54 UTC
Labels: duplicate
