### ISSUE TITLE
Install libraries failed on Lesson 28 Alpha Factor Research Method

### ISSUE THREAD

**Issue by aa-wong** [udacity/aitnd-issues#103] opened 2019-03-13 21:23 UTC
Error returned the following 

"Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mmzukpvt/tables/

You are using pip version 9.0.1, however version 19.0.3 is available.

You should consider upgrading via the 'pip install --upgrade pip' command."

**Comment by aa-wong** [comment] 2019-03-13 21:25
Additional details:

ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.

**Comment by Brok-Bucholtz** [comment] 2019-03-15 21:01
Duplicate of issue #102.

**Comment by Brok-Bucholtz** [comment] 2019-03-25 05:54
This should be working again.

**Closed as completed by Brok-Bucholtz** 2019-03-25 05:54 UTC
