### ISSUE TITLE
Lesson 24: Still loading Libraries for each exercise

### ISSUE THREAD

**Issue by Seananigans** [udacity/aitnd-issues#84] opened 2018-12-19 20:13 UTC

**Comment by e7dud7e** [comment] 2018-12-21 21:42
Hi Sean, thanks for letting us know.  Can you gives your email that you use with your Udacity account?  I can follow up with the engineering team about this.

**Comment by Seananigans** [comment] 2018-12-24 04:12
sph99@comcast.net

**Comment by Seananigans** [comment] 2019-01-07 00:48
I still haven't received any feedback on this issue and I'm still having the same problem.

**Comment by e7dud7e** [comment] 2019-01-09 19:00
Hi Sean, I went into your account to troubleshoot. The first time in lesson 24, it does take ~9 minutes; for the subsequent notebooks within lesson 24, it was much faster (< 30 seconds).  I did the same with lesson 27.  Are you still having an issue with the installation taking a long time for each notebook within the same lesson?  Thanks!

**Comment by Brok-Bucholtz** [comment] 2019-01-25 22:46
This is a duplicate of Issue #85.

**Closed as completed by Brok-Bucholtz** 2019-01-25 22:46 UTC
Labels: duplicate
