### ISSUE TITLE
Historical Variance

### ISSUE THREAD

**Issue by cmkwong** [udacity/aitnd-issues#96] opened 2019-02-15 17:38 UTC
After install the library, it has error still:
ImportError: cannot import name 'ABCIndexClass'

**Comment by lizotto** [comment] 2019-02-15 20:43
Hi @cmkwong, in what part of the course does this error occur? Can you give the lesson #?

**Comment by e7dud7e** [comment] 2019-02-15 22:22
Hi! Thanks for notifying us.  I wasn't able to re-produce this error.  Could you try to refresh your workspace using "reset data"?  If you still get this error, please let us know, thank you!

**Comment by cmkwong** [comment] 2019-02-16 14:19
The issue occurs in Term 1 Lesson 24-4. It seems no problem now when Kernel > Restart and Run All. But I need to install every time when I restart the jupyter notebook?

**Comment by Brok-Bucholtz** [comment] 2019-02-22 18:12
This is a duplicate of Issue #85.

**Closed as completed by Brok-Bucholtz** 2019-02-22 18:12 UTC
