### ISSUE TITLE
waiting a long time for 'pip install' for each coding exercise

### ISSUE THREAD

**Issue by ememdev** [udacity/aitnd-issues#89] opened 2019-01-21 18:07 UTC

**Comment by ememdev** [comment] 2019-01-21 18:09
i thought it was just part of the coding, but after reading the info in lesson 27, realize that each time i work through a lesson (or if my workspace goes to sleep), i need to re-run the installation requirements, which takes 8 or 9 minutes

**Comment by ememdev** [comment] 2019-01-23 15:06
Still having issues for Lesson 27 - anytime my workspace 'times out' or needs to be refreshed (ie, switching between videos & jupyter workspace), there libraries need to be re-installed and it takes another ~9 minutes.

**Comment by ememdev** [comment] 2019-01-23 16:49
more specific recent example, for lesson 27: the 'ranking' exercise (27.12) had me install the requirements (long wait time while being installed).. i then finished that, watched videos on parts *.13, *.14 and then moved on to 27.15 - the z-score exercise. but for this exercise too, the workspace is re-installing all the same libraries that it just installed for part *.12 - why?!? there was no refresh or timeout this time - just moving through the lesson.
is this expected behavior or can something be updated in my settings to not have to reinstall each time - these waits are beyond inconvenient and a real pain.

**Comment by Brok-Bucholtz** [comment] 2019-01-25 22:03
This is a duplicate of Issue #85

**Closed as completed by Brok-Bucholtz** 2019-01-25 22:03 UTC
Labels: duplicate
