### ISSUE TITLE
Issues with the installation code

### ISSUE THREAD

**Issue by youngkyungkim** [udacity/aitnd-issues#76] opened 2018-11-30 22:49 UTC
If you notice that you're waiting 8 to 9 minutes on the pip install code cell for every code exercise, please add a ticket to the waffleboard 

I have this problem.....

**Comment by e7dud7e** [comment] 2018-12-04 19:17
Hi Young Kyung, thanks for notifying us of this so that we can follow up.  Is this happening in the "risk factors" lesson?  Or the "alpha factors" lesson?

**Comment by e7dud7e** [comment] 2018-12-04 20:15
Hi Young Kyung, thanks again for identifying this issue.  I tried running the installation in your workspace, (in risk factors), and it did need to install the first time, but then when I ran other notebooks within the same lesson, the installation was still intact, so the installation completed quickly.  If you can still see this issue, can you describe how to reproduce it?  Thanks!  Also, note that when you go to a new lesson, you'll still need to install the packages once. Thanks!

**Comment by Brok-Bucholtz** [comment] 2019-01-25 22:30
This is a duplicate of Issue #85.

**Closed as completed by Brok-Bucholtz** 2019-01-25 22:30 UTC
Labels: duplicate
