### ISSUE TITLE
Lesson 24: pip install takes long after sesion expiration

### ISSUE THREAD

**Issue by cristian-spiescu** [udacity/aitnd-issues#98] opened 2019-02-20 12:44 UTC

**Comment by cristian-spiescu** [comment] 2019-02-20 12:48
Cf. instructions, I write here to report issues. I logged in, ran the first notebook which took long, as expected (it's written: 8 - 9 minutes, but I didn't measure). Then I worked with a couple of notebooks. pip install reported "deps already met". So everything was fine.

I went to lunch. Bot back. I refreshed the notebook. The session expired, so probably I was given another VM. And now it takes long for the first pip install.

**Comment by Brok-Bucholtz** [comment] 2019-02-22 18:12
This is a duplicate of Issue #85.

**Closed as completed by Brok-Bucholtz** 2019-02-22 18:12 UTC
