### ISSUE TITLE
pip install keeps taking minutes - each exercise

### ISSUE THREAD

**Issue by mirkosavasta** [udacity/aitnd-issues#100] opened 2019-03-10 18:02 UTC
I followed the instructions and run the pip cell for the first exercise. But at the second exercise (point 6 - Lesson 24) the problem occurred again and now I am waiting for that cell to finish execution.

**Comment by Brok-Bucholtz** [comment] 2019-03-15 21:10
This is a duplicate of Issue #85.

**Closed as completed by Brok-Bucholtz** 2019-03-15 21:10 UTC
